site_name: Pycharm and Git User Guide
theme:
  name: material
  palette:
    primary: deep orange

  features:
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
