site_name: Using Git, and GitHub to Manage Your Code
theme:
  name: material
  palette:
    primary: indigo

  features:
    - toc.integrate
    - navigation.footer

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: 'index.md'
  - 'gettingStarted.md'
  - 'pullingAndMerge.md'
  - 'forksAndPR.md'
  - 'troubleshooting.md'
  - 'glossary.md'
