site_name: Using Git, GitHub, and Visual Studio Code to Manage Your Code
theme:
  name: material
  palette:
    primary: deep orange

  features:
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: 'index.md'
  - 'gettingStarted.md'
  - 'Pulling.md'
  - 'forksAndPR.md'
  - 'glossary.md'
